Add restore action
tcpcloud/python-aptly pull request #4
Opened 2017-07-04 14:56 UTC by chnyda

2017-07-13 13:04 UTC, fpytloun requested changes

2017-07-13 13:04 UTC, fpytloun commented on aptly/publisher/__init__.py
> +    def save_publish(self, aptly_dir="/srv/aptly/"):
Don't use any default for output directory, that should be mandatory option, or default to current working directory

2017-07-13 13:04 UTC, fpytloun commented on aptly/publisher/__init__.py
> +        file_name = aptly_dir + name + "-" + time.strftime("%Y%m%d%H%M%S")
Use format instead of concating strings this way

2017-07-13 13:04 UTC, fpytloun commented on aptly/publisher/__init__.py
> +        lg.info("Saving publish %s in %s" % (name, file_name))
Should probably contain whole path not only filename, use os.path.join for it

2017-07-13 13:04 UTC, fpytloun commented on aptly/publisher/__init__.py
> +            save_file.write("publish: %s\n" % self.name)
Instead of writing yaml manually, create dict structure and use `yaml.dump` - http://pyyaml.org/wiki/PyYAMLDocumentation#DumpingYAML

2017-07-13 13:04 UTC, fpytloun commented on aptly/publisher/__init__.py
> +            self.save_publish()
I don't think you should do this action by default on restore, user should do it on it's own

2017-07-13 13:04 UTC, fpytloun commented on aptly/publisher/__init__.py
> +        for saved_component in config.get('components'):
`config.get('components', [])` to default to empty list

2017-07-13 13:04 UTC, fpytloun commented on aptly/publisher/__init__.py
> +            component_name = saved_component.get('component')
if there's no component name, then file is corrupted and you should probably fail here

2017-07-13 13:04 UTC, fpytloun commented on aptly/publisher/__init__.py
> +            if components and component_name not in components:
where's `components` defined?

2017-07-13 13:04 UTC, fpytloun commented on aptly/publisher/__init__.py
> +            snapshot_name = ''.join([component_name, '-', time.strftime("%Y%m%d%H%M%S")])
format would be better than join

2017-07-13 13:04 UTC, fpytloun commented on aptly/publisher/__init__.py
> +            lg.debug("Creating snapshot %s for component %s of packages: %s" % (snapshot_name, component_name, saved_packages))
What if snapshot already exists?

2017-07-13 13:04 UTC, fpytloun commented on aptly/publisher/__init__.py
> +            lg.debug("Creating snapshot %s for component %s of packages: %s" % (snapshot_name, component_name, saved_packages))
Also snapshot name should include prefix, etc. Resp. it should be exactly the same as original snapshot, including description, etc. - these informations should be probably also saved and restored.

2017-07-13 13:04 UTC, fpytloun commented on aptly/publisher/__init__.py
> +        if recreate and publish:
Shouldn't you call do_publish method instead of duplicating code?

2017-07-13 13:04 UTC, fpytloun commented on aptly/publisher/__main__.py
> +    parser.add_argument('action', help="Action to perform (publish, promote, cleanup, restore, save)")
I would rename save to dump instead to be more meaningful

2017-07-13 13:04 UTC, fpytloun commented on aptly/publisher/__main__.py
> +    group_common.add_argument('--components', nargs='+', help="Space-separated list of components to promote")
`to promote or restore`

2017-07-13 13:04 UTC, fpytloun commented on aptly/publisher/__main__.py
> +    group_save.add_argument('-p', '--publish', help="Publish to save")
Publish to dump, defaults to all

2017-07-13 13:04 UTC, fpytloun commented on aptly/publisher/__main__.py
> +    group_restore.add_argument('-r', '--restorefile', help="File used to restore publish")
`--restore-file`

2017-07-13 13:04 UTC, fpytloun commented on aptly/publisher/__main__.py
> +        publish_target.save_publish()
This should not happen by default

2017-07-13 13:04 UTC, fpytloun commented on aptly/publisher/__main__.py
> +    publish = Publish(client, publish_to_save, load=True)
Should iterate over all publishes and dump all if publish_to_save is not set

2017-07-13 13:04 UTC, fpytloun commented on aptly/publisher/__main__.py
> +    publish_file = load_publish(restore_file)
Let `restore_publish` method load the file, don't load it from main

2017-07-13 13:07 UTC, chnyda commented on aptly/publisher/__init__.py
> +            if components and component_name not in components:
components is a parameter of the function. We might want to restore only some components. Or you are against it?

2017-07-13 13:07 UTC, fpytloun commented
@pep8speaks Resume now.

2017-07-13 13:08 UTC, fpytloun commented on aptly/publisher/__init__.py
> +            if components and component_name not in components:
Ok, I missed that

2017-07-14 14:22 UTC, pep8speaks commented
Hello @chnyda! Thanks for updating the PR.

 - In the file [`aptly/publisher/__init__.py`](https://github.com/tcpcloud/python-aptly/blob/2936869988785dfdf83b4527abe9f465e7eb85ad/aptly/publisher/__init__.py), following are the PEP8 issues :

> [Line 28:80](https://github.com/tcpcloud/python-aptly/blob/2936869988785dfdf83b4527abe9f465e7eb85ad/aptly/publisher/__init__.py#L28): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (104 > 79 characters)
> [Line 48:25](https://github.com/tcpcloud/python-aptly/blob/2936869988785dfdf83b4527abe9f465e7eb85ad/aptly/publisher/__init__.py#L48): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 56:17](https://github.com/tcpcloud/python-aptly/blob/2936869988785dfdf83b4527abe9f465e7eb85ad/aptly/publisher/__init__.py#L56): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 60:5](https://github.com/tcpcloud/python-aptly/blob/2936869988785dfdf83b4527abe9f465e7eb85ad/aptly/publisher/__init__.py#L60): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 86:80](https://github.com/tcpcloud/python-aptly/blob/2936869988785dfdf83b4527abe9f465e7eb85ad/aptly/publisher/__init__.py#L86): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 113:80](https://github.com/tcpcloud/python-aptly/blob/2936869988785dfdf83b4527abe9f465e7eb85ad/aptly/publisher/__init__.py#L113): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 125:80](https://github.com/tcpcloud/python-aptly/blob/2936869988785dfdf83b4527abe9f465e7eb85ad/aptly/publisher/__init__.py#L125): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (96 > 79 characters)
> [Line 134:80](https://github.com/tcpcloud/python-aptly/blob/2936869988785dfdf83b4527abe9f465e7eb85ad/aptly/publisher/__init__.py#L134): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (107 > 79 characters)
> [Line 191:80](https://github.com/tcpcloud/python-aptly/blob/2936869988785dfdf83b4527abe9f465e7eb85ad/aptly/publisher/__init__.py#L191): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (92 > 79 characters)
> [Line 193:80](https://github.com/tcpcloud/python-aptly/blob/2936869988785dfdf83b4527abe9f465e7eb85ad/aptly/publisher/__init__.py#L193): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 196:80](https://github.com/tcpcloud/python-aptly/blob/2936869988785dfdf83b4527abe9f465e7eb85ad/aptly/publisher/__init__.py#L196): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 79 characters)
> [Line 198:80](https://github.com/tcpcloud/python-aptly/blob/2936869988785dfdf83b4527abe9f465e7eb85ad/aptly/publisher/__init__.py#L198): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 234:80](https://github.com/tcpcloud/python-aptly/blob/2936869988785dfdf83b4527abe9f465e7eb85ad/aptly/publisher/__init__.py#L234): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (100 > 79 characters)
> [Line 236:56](https://github.com/tcpcloud/python-aptly/blob/2936869988785dfdf83b4527abe9f465e7eb85ad/aptly/publisher/__init__.py#L236): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 237:17](https://github.com/tcpcloud/python-aptly/blob/2936869988785dfdf83b4527abe9f465e7eb85ad/aptly/publisher/__init__.py#L237): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 237:27](https://github.com/tcpcloud/python-aptly/blob/2936869988785dfdf83b4527abe9f465e7eb85ad/aptly/publisher/__init__.py#L237): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 238:30](https://github.com/tcpcloud/python-aptly/blob/2936869988785dfdf83b4527abe9f465e7eb85ad/aptly/publisher/__init__.py#L238): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 239:27](https://github.com/tcpcloud/python-aptly/blob/2936869988785dfdf83b4527abe9f465e7eb85ad/aptly/publisher/__init__.py#L239): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 277:21](https://github.com/tcpcloud/python-aptly/blob/2936869988785dfdf83b4527abe9f465e7eb85ad/aptly/publisher/__init__.py#L277): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 283:80](https://github.com/tcpcloud/python-aptly/blob/2936869988785dfdf83b4527abe9f465e7eb85ad/aptly/publisher/__init__.py#L283): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 285:17](https://github.com/tcpcloud/python-aptly/blob/2936869988785dfdf83b4527abe9f465e7eb85ad/aptly/publisher/__init__.py#L285): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 303:80](https://github.com/tcpcloud/python-aptly/blob/2936869988785dfdf83b4527abe9f465e7eb85ad/aptly/publisher/__init__.py#L303): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (94 > 79 characters)
> [Line 306:28](https://github.com/tcpcloud/python-aptly/blob/2936869988785dfdf83b4527abe9f465e7eb85ad/aptly/publisher/__init__.py#L306): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 307:23](https://github.com/tcpcloud/python-aptly/blob/2936869988785dfdf83b4527abe9f465e7eb85ad/aptly/publisher/__init__.py#L307): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 311:80](https://github.com/tcpcloud/python-aptly/blob/2936869988785dfdf83b4527abe9f465e7eb85ad/aptly/publisher/__init__.py#L311): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (146 > 79 characters)
> [Line 311:145](https://github.com/tcpcloud/python-aptly/blob/2936869988785dfdf83b4527abe9f465e7eb85ad/aptly/publisher/__init__.py#L311): [E202](https://duckduckgo.com/?q=pep8%20E202) whitespace before ']'
> [Line 312:80](https://github.com/tcpcloud/python-aptly/blob/2936869988785dfdf83b4527abe9f465e7eb85ad/aptly/publisher/__init__.py#L312): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (97 > 79 characters)
> [Line 315:80](https://github.com/tcpcloud/python-aptly/blob/2936869988785dfdf83b4527abe9f465e7eb85ad/aptly/publisher/__init__.py#L315): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (102 > 79 characters)
> [Line 334:80](https://github.com/tcpcloud/python-aptly/blob/2936869988785dfdf83b4527abe9f465e7eb85ad/aptly/publisher/__init__.py#L334): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (90 > 79 characters)
> [Line 350:80](https://github.com/tcpcloud/python-aptly/blob/2936869988785dfdf83b4527abe9f465e7eb85ad/aptly/publisher/__init__.py#L350): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (92 > 79 characters)
> [Line 399:80](https://github.com/tcpcloud/python-aptly/blob/2936869988785dfdf83b4527abe9f465e7eb85ad/aptly/publisher/__init__.py#L399): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 414:80](https://github.com/tcpcloud/python-aptly/blob/2936869988785dfdf83b4527abe9f465e7eb85ad/aptly/publisher/__init__.py#L414): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (119 > 79 characters)
> [Line 422:80](https://github.com/tcpcloud/python-aptly/blob/2936869988785dfdf83b4527abe9f465e7eb85ad/aptly/publisher/__init__.py#L422): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (146 > 79 characters)
> [Line 426:80](https://github.com/tcpcloud/python-aptly/blob/2936869988785dfdf83b4527abe9f465e7eb85ad/aptly/publisher/__init__.py#L426): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 430:80](https://github.com/tcpcloud/python-aptly/blob/2936869988785dfdf83b4527abe9f465e7eb85ad/aptly/publisher/__init__.py#L430): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (167 > 79 characters)
> [Line 432:80](https://github.com/tcpcloud/python-aptly/blob/2936869988785dfdf83b4527abe9f465e7eb85ad/aptly/publishe [...]

2017-07-19 14:04 UTC, merged